%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%                Optical Analysis: GUI Interface v 1.1               %%%
%%%                       Last Updated: 7/12/2018                      %%% 
%%%              Author:  Daniel Li (daniel_li2@brown.edu)             %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%% RUN THIS GUI FOR ALL OPTICAL ANALYSIS TOOLS IN ONE LOCATION

function [] = optical_GUI()

gui = figure('Visible','on',...
    'Position',[1100 400 300 400],...
    'Numbertitle','off',...
    'Units','normalized',...
    'Name','Optic Analysis GUI');

t1 = uicontrol('Style','text',...
    'String','Analysis Tools',...
    'FontWeight','bold',...
    'FontSize',12,...
    'Position',[80 370 140 20],...
    'Units','normalized');

t2 = uicontrol('Style','edit',...
    'unit','pix',...
    'position',[20 10 260 20],...
    'String','None',...
    'Units','normalized');

t3 = uicontrol('Style','text',...
    'position',[20 35 260 20],...
    'fontweight','bold',...
    'horizontalalign','left',...
    'fontsize',10,...
    'String','Currently Running: ',...
    'Units','normalized');

t4 = uicontrol('Style','text',...
    'String','Visualization Tools',...
    'FontWeight','bold',...
    'FontSize',12,...
    'Position',[20 220 260 20],...
    'Units','normalized');

p1 = uicontrol('Style','pushbutton',...
    'String','View Single Spectrum',...
    'Position',[20 180 260 30],...
    'Units','normalized',...
    'tooltip',['Select a single .txt data file and plot with the ' 10,...
    'ability to include linse at given x-values.'],...
    'Callback',@p1_call);

p2 = uicontrol('Style','pushbutton',...
    'String','View/Manipulate Multiple Spectra',...
    'Position',[20 140 260 30],...
    'Units','normalized',...
    'tooltip',['Can plot any number of spectra until chosen to ' 10,...
    'stop and can also scale selected data to normalize spectra ' 10,...
    'against one another.  Lastly, additional plots of the ratio ' 10,...
    'of the subsequent data files following the first to the' 10,...
    'first data file is plotted'],...
    'Callback',@p2_call);

p3 = uicontrol('Style','pushbutton',...
    'String','Average Spectra',...
    'Position',[20 330 260 30],...
    'Units','normalized',...
    'tooltip',['Can select up to any number of spectra and averages ' 10,...
    'them and additionally computes the variance and a binning ' 10,...
    'quality metric to gauge how consistent the data files are to ' 10,...
    'one another'],...
    'Callback',@p3_call);

p4 = uicontrol('Style','pushbutton',...
    'String','Peak Finder (Polynomial)',...
    'Position',[20 290 260 30],...
    'Units','normalized',...
    'tooltip',['Selects a single data file and allows the user to ' 10,...
    'estimate where the peak location will be and how many points ' 10,...
    'will be used for the polynomial fit (up to n = 4).  Plots of ' 10,...
    'the raw data superimposed with the fit and calculated peak ' 10,...
    'location generated.'],...
    'Callback',@p4_call);

p5 = uicontrol('Style','pushbutton',...
    'String','[OH] Determination',...
    'Position',[20 250 260 30],...
    'Units','normalized',...
    'tooltip',['Gives the user the option to use a reference data ' 10,...
    'file or not, and then estimates the OH concentration for ' 10,...
    'either Raman or Absorption data.'],...
    'Callback',@p5_call);

p6 = uicontrol('Style','pushbutton',...
    'String','Raman Peak Locations',...
    'Position',[20 100 260 30],...
    'Units','normalized',...
    'tooltip',['Provides a set of known Raman peaks for fused ' 10,...
    'silica and allows the user to import data and visualize ' 10,...
    'where peaks would fit onto their data.'],...
    'Callback',@p6_call);

p7 = uicontrol('Style','pushbutton',...
    'String','Model Fit Center Estimate',...
    'Position',[20 60 260 30],...
    'Units','normalized',...
    'tooltip',['Takes in a three column .txt file with ''Points ' 10,...
    'Used'', ''Center Estimate'', and ''Adj. Chi-Square'' and plots ' 10,...
    'the Center Estimate and Adj. Chi-Square against the points used. ' 10,...
    'Good for optimizing model fit parameters (i.e. minimizing chi-sq).'],...
    'Callback',@p7_call);

end

function [] = p1_call(hObject,eventdata,handles,varargin)

t2 = uicontrol('Style','edit',...
    'unit','pix',...
    'position',[20 10 260 20],...
    'String','View Single Spectrum');
uiwait(msgbox('Choose data file (.txt) to view.'));
View_Spectrum;
end

function [] = p2_call(varargin)
t2 = uicontrol('Style','edit',...
    'unit','pix',...
    'position',[20 10 260 20],...
    'String','View/Manipulate Multiple Spectra');
Multi_peak;
end

function [] = p3_call(varargin)
t2 = uicontrol('Style','edit',...
    'unit','pix',...
    'position',[20 10 260 20],...
    'String','Average Spectra');
Spectrum_data_avg;
end

function [] = p4_call(varargin)
t2 = uicontrol('Style','edit',...
    'unit','pix',...
    'position',[20 10 260 20],...
    'String','Peak Finder (Polynomial)');
Peak_Find;
end

function [] = p5_call(varargin)
t2 = uicontrol('Style','edit',...
    'unit','pix',...
    'position',[20 10 260 20],...
    'String','View Single Spectrum');
OH_concentration;
end

function [] = p6_call(varargin)
t2 = uicontrol('Style','edit',...
    'unit','pix',...
    'position',[20 10 260 20],...
    'String','Raman Peak Locations');
raman_sio2_GUI;
end

function [] = p7_call(varargin)
t2 = uicontrol('Style','edit',...
    'unit','pix',...
    'position',[20 10 260 20],...
    'String','Model Fit Center Estimate');
center_est_qual;
end