%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%                 Raman SiO2 Peak Visualization v 1.1                %%%
%%%                       Last Updated: 7/12/2018                      %%%
%%%              Author:  Daniel Li (daniel_li2@brown.edu)             %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%% THIS APP TAKES IN A SINGLE RAMAN SPECTRUM AND ALLOWS THE USER TO 
%%% VISUALIZE COMMON RAMAN PEAK LOCATIONS AND PROVIDES PHYSICAL
%%% DESCRIPTIONS FOR THOSE LINES PROVIDED.  THIS IS NOT SO MUCH AN ANALYTIC
%%% TOOL, BUT MORE SO A VISUALIZATION ONE THAT HAS THE BENEFIT OF 
%%% EDUCATING A USER NEW TO RAMAN AND FUSED SILICA ON THE CHARACTERISTICS
%%% OF FUSED SILICA STRUCTURE

%%% THIS FUNCTION IS THE GUI CONTAINING ALL THE GRAPHICS SEEN ON THE 
%%% INTERFACE (I.E. CHECKBOXES, DESCRIPTIONS, PUSH BUTTONS, AND GRAPH/AXES)
%%% MUCH DETAIL IS PUT INTO THE LAYOUT SUCH THAT CARE SHOULD BE TAKEN IF
%%% ADJUSTING A SINGLE ASPECT (I.E. THE GUI DIMENSIONS)
function [] = raman_sio2_GUI()

%%% GUI FIGURE DIMENSIONS (OUTER BOX)
S.f1 = figure('Visible','on',...
    'Position',[100 400 1000 540],...
    'Numbertitle','off',...
    'Units','normalized',...
    'Name','Raman Peaks for SiO2',...
    'Color','w');

%%% PUSH BUTTONS
S.p1 = uicontrol('Style','pushbutton',...
    'String','Plot Spectra',...
    'FontSize',10,...
    'Position',[570 40 120 25],...
    'Units','normalized');

S.p2 = uicontrol('Style','pushbutton',...
    'String','Select Data',...
    'FontSize',10,...
    'Position',[710 40 120 25],...
    'Units','normalized',...
    'Callback',{@p2_call,S});

S.p3 = uicontrol('Style','pushbutton',...
    'String','Save Spectra',...
    'FontSize',10,...
    'Position',[850 40 120 25],...
    'Units','normalized',...
    'Callback',{@p3_call,S});

%%% TEXT/EDIT BOXES
S.t1 = uicontrol('Style','text',...
    'position',[20,510,130,20],...
    'fontweight','bold',...
    'horizontalalign','left',...
    'fontsize',10,...
    'Units','normalized',...
    'backgroundcol',[1 1 1],...
    'String','Intrinsic Peaks');

S.t2 = uicontrol('Style','text',...
    'position',[150,510,200,20],...
    'fontweight','bold',...
    'horizontalalign','left',...
    'fontsize',10,...
    'Units','normalized',...
    'backgroundcol',[1 1 1],...
    'String','Description');

S.t3 = uicontrol('Style','edit',...
    'position',[665,10,305,20],...
    'Unit','normalized',...
    'FontSize',9,...
    'horizontalalign','left',...
    'String','None');

S.t4 = uicontrol('Style','text',...
    'position',[570,8,90,20],...
    'Unit','normalized',...
    'FontWeight','bold',...
    'FontSize',9,...
    'horizontalalign','left',...
    'backgroundcol',[1 1 1],...
    'String','Data Selected: ');

S.t5 = uicontrol('Style','text',...
    'position',[20,280,120,20],...
    'fontweight','bold',...
    'horizontalalign','left',...
    'fontsize',10,...
    'Units','normalized',...
    'backgroundcol',[1 1 1],...
    'String','Hydroxyl Peaks');

S.t6 = uicontrol('Style','text',...
    'position',[20,180,120,20],...
    'fontweight','bold',...
    'horizontalalign','left',...
    'fontsize',10,...
    'Units','normalized',...
    'backgroundcol',[1 1 1],...
    'String','Interstitial Peaks');

S.t7 = uicontrol('Style','text',...
    'position',[20,75,120,20],...
    'fontweight','bold',...
    'horizontalalign','left',...
    'fontsize',10,...
    'Units','normalized',...
    'backgroundcol',[1 1 1],...
    'String','Other Peaks');

%%% GRAPH
S.a1 = axes('Units','pixels',...
    'Position',[580,130,380,360],...
    'Units','normalized');

%%% CHECK BOXES AND DESCRIPTIONS FOR THE RAMAN PEAKS
S.peak68 = uicontrol('Style','checkbox',...
    'Position',[20,490,100,15],...
    'String','Boson Peak ~ 68',...
    'backgroundcol',[1 1 1],...
    'Units','normalized');

S.text68 = uicontrol('Style','text',...
    'Position',[150,491,380,15],...
    'String',['Non-polar optical excitation, attributed ',...
    'to rotation of SiO4 structure.'],...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

S.peak490 = uicontrol('Style','checkbox',...
    'Position',[20,465,100,15],...
    'String','<html>D<sub>1</sub> ~ 490</html>',...
    'backgroundcol',[1 1 1],...
    'Units','normalized');

S.text490 = uicontrol('Style','text',...
    'Position',[150,466,380,15],...
    'String','Fourfold SiO4 ring symmetric stretching',...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

S.peak606 = uicontrol('Style','checkbox',...
    'Position',[20,440,100,15],...
    'backgroundcol',[1 1 1],...
    'Units','normalized',...
    'String','<html>D<sub>2</sub> ~ 606</html>');

S.text606 = uicontrol('Style','text',...
    'Position',[150,441,380,15],...
    'String','Threefold SiO4 ring symmetric stretching',...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

S.peak437 = uicontrol('Style','checkbox',...
    'Position',[20,415,100,15],...
    'String','<html>&omega<sub>1</sub> ~ 437</html>',...
    'backgroundcol',[1 1 1],...
    'Units','normalized');

S.text437 = uicontrol('Style','text',...
    'Position',[150,416,380,15],...
    'String','Pure bending motion of SiO2',...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

S.peak830 = uicontrol('Style','checkbox',...
    'Position',[20,390,100,15],...
    'backgroundcol',[1 1 1],...
    'String','<html>&omega<sub>2</sub> ~ 830</html>',...
    'Units','normalized');

S.text830 = uicontrol('Style','text',...
    'Position',[150,391,380,15],...
    'String','Pure stretching motion of SiO2',...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

S.peak797 = uicontrol('Style','checkbox',...
    'Position',[20,365,100,15],...
    'backgroundcol',[1 1 1],...
    'String','<html>&omega<sub>3</sub> ~ 797</html>',...
    'Units','normalized');

S.text797 = uicontrol('Style','text',...
    'Position',[150,366,380,15],...
    'String','No stretching motion of SiO2',...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

S.peakw4TO = uicontrol('Style','checkbox',...
    'Position',[20,340,100,15],...
    'backgroundcol',[1 1 1],...
    'String','<html>&omega<sub>4,TO</sub> ~ 1060</html>',...
    'Units','normalized');

S.textw4TO = uicontrol('Style','text',...
    'Position',[150,341,380,15],...
    'String','No bending motion of SiO2, transverse optical',...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

S.peakw4LO = uicontrol('Style','checkbox',...
    'Position',[20,315,100,15],...
    'backgroundcol',[1 1 1],...
    'String','<html>&omega<sub>4,LO</sub> ~ 1190</html>',...
    'Units','normalized');

S.textw4LO = uicontrol('Style','text',...
    'Position',[150,316,380,15],...
    'String','No bending motion of SiO2, longitudinal optical',...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

S.peak3700 = uicontrol('Style','checkbox',...
    'Position',[20,260,100,15],...
    'backgroundcol',[1 1 1],...
    'String','SiO-H ~ 3700',...
    'Units','normalized');

S.text3700 = uicontrol('Style','text',...
    'Position',[150,261,380,15],...
    'String','Bond between O and H in Si-bound hydroxyl',...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

S.peak980f = uicontrol('Style','checkbox',...
    'Position',[20,235,100,15],...
    'backgroundcol',[1 1 1],...
    'String','Si-OH(f) ~ 980',...
    'Units','normalized');

S.text980f = uicontrol('Style','text',...
    'Position',[150,236,380,15],...
    'String','The Si-bound hydroxyl acts as a free radical',...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

S.peak920b = uicontrol('Style','checkbox',...
    'Position',[20,210,100,15],...
    'backgroundcol',[1 1 1],...
    'String','Si-OH(b) ~ 920',...
    'Units','normalized');

S.text920b = uicontrol('Style','text',...
    'Position',[150,211,380,15],...
    'String','The Si-bound hydroxyl is H-bonded, as well',...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

S.peak1540 = uicontrol('Style','checkbox',...
    'Position',[20,155,100,15],...
    'backgroundcol',[1 1 1],...
    'String','<html>O<sub>2</sub> ~ 1540</html>',...
    'Units','normalized');

S.text1540 = uicontrol('Style','text',...
    'Position',[150,156,380,15],...
    'String','O2 trapped in network lattice (not part of)',...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

S.peak4135 = uicontrol('Style','checkbox',...
    'Position',[20,130,100,15],...
    'backgroundcol',[1 1 1],...
    'String','<html>H<sub>2</sub> ~ 4135</html>',...
    'Units','normalized');

S.text4135 = uicontrol('Style','text',...
    'Position',[150,131,380,15],...
    'String','H2 trapped in network lattice (not part of)',...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

S.peak2331 = uicontrol('Style','checkbox',...
    'Position',[20,105,100,20],...
    'backgroundcol',[1 1 1],...
    'String','<html>N<sub>2</sub> ~ 2331</html>',...
    'Units','normalized');

S.text2331 = uicontrol('Style','text',...
    'Position',[150,106,380,15],...
    'String','N2 trapped in network lattice (not part of)',...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

S.peak945 = uicontrol('Style','checkbox',...
    'Position',[20,50,100,20],...
    'backgroundcol',[1 1 1],...
    'String','F ~ 945',...
    'Units','normalized');

S.text945 = uicontrol('Style','text',...
    'Position',[150,51,380,15],...
    'String','Common dopant in fused silica to reduce n',...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

S.peak2900 = uicontrol('Style','checkbox',...
    'Position',[20,25,100,20],...
    'backgroundcol',[1 1 1],...
    'String','<html>C<sub>x</sub>H<sub>y</sub> ~ 2900</html>',...
    'Units','normalized');

S.text2900 = uicontrol('Style','text',...
    'Position',[150,26,380,15],...
    'String','Most likely a saturated hydrocarbon',...
    'backgroundcol',[1 1 1],...
    'horizontalalign','left',...
    'Units','normalized');

%%% ASSIGNS AN OUTER FUNCTION TO EACH PUSH BUTTON
set(S.p1,'callback',{@p1_call,S});
set(S.p2,'callback',{@p2_call,S});
set(S.p3,'callback',{@p3_call,S});

%%% CALLBACK FOR THE 'PLOT SPECTRA' PUSH BUTTON
function [] = p1_call(varargin)

%%% CALL STRUCTURE 'S' (I.E. IMPORTS FROM THE HOST FUNCTION)
S = varargin{3};
str = get(S.t3,'String');

%%% ONLY ALLOWS PLOTTING IF DATA IS SELECTED
if strcmp(str,'None')
    msgbox('Must select data to view spectra.');
else
    
%%% REFERS TO THE 'DATA SELECTED' EDIT BOX TO CALL DESIRED FILE FROM
%%% DESTINATION IN COMPUTER AND THEN PLOTS THE DATA FILE AND RAMAN LINES
    cla(S.a1);
    data = dlmread(fullfile(str),'\t');
    data_x = data(:,1);
    data_y = data(:,2);
    
    axes(S.a1);
    plot(data_x,data_y,'color',[0.9 0.3 0.3]);
    xlabel('Frequency cm^{-1}','FontSize',9);
    ylabel('Counts','FontSize',9);
    grid on;
    grid minor;
    
%%% ADDS THE RAMAN LINES

%%% HOLDS THE RAMAN PEAK LOCATIONS IN THE SAME ORDER AS THE CHECK BOXES
%%% ON THE GUI.  IF YOU WANT TO ADD A NEW RAMAN LINE OPTION TO THE GUI
%%% BE SURE TO EDIT THIS ARRAY BY INSERTING IN THE NEW VALUE IN SEQUENTIAL
%%% ORDER
    peak_arr = [68 490 606 437 830 797 1060 1190 3700 980 920 1540 ...
        4135 2331 945 2900];
    
%%% HOLDS THE RAMAN PEAK NAMES TO INCLUDE WITH THE RAMAN LINES PLOTTED.
    peak_name_arr = {'Boson Peak','D_1','D_2','\omega_1','\omega_2',...
        '\omega_3','\omega_{4,TO}','\omega_{4,LO}','SiO-H','Si-OH(f)',...
        'Si-OH(b)','O_2','H_2','N_2','F','C_xH_y'};
    
%%% HOLDS ALL THE VALUES OF THE CHECK BOXES (I.E. CHECKED OR UN-CHECKED)
%%% AND WILL BE CROSS-REFERENCED WITH THE PEAK_ARR TO PLOT RAMAN LINES
    check_arr = [get(S.peak68,'val') get(S.peak490,'val')...
        get(S.peak606,'val') get(S.peak437,'val') get(S.peak830,'val')...
        get(S.peak797,'val') get(S.peakw4TO,'val') get(S.peakw4LO,'val')...
        get(S.peak3700,'val') get(S.peak980f,'val') get(S.peak920b,'val')...
        get(S.peak1540,'val') get(S.peak4135,'val') get(S.peak2331,'val')...
        get(S.peak945,'val') get(S.peak2900,'val')];
    
    hold on
    for n = 1:length(peak_arr)
       if check_arr(n) ==  1
           line([peak_arr(n); peak_arr(n)],[0; max(data_y)*1.2],...
               'color',[0 0 0],...
               'LineStyle','--',...
               'LineWidth',0.5,...
               'Clipping','on');
           text(peak_arr(n)+10,max(data_y)*0.05*n,...
               peak_name_arr{n},...
               'FontSize',8);
       end
    end
    hold off
    ylim([0 max(data_y)*1.2]);
    title(inputdlg('Enter Title for Spectrum'));
end

%%% SELECT DATA FROM COMPUTER
function [] = p2_call(varargin)

S = varargin{3};
[file,path] = uigetfile('*.txt');

file_path = strcat(path,file);

set(S.t3,'String',file_path)


%%% SAVE THE SPECTRA FROM GUI INTERFACE AND PRODUCES A NEW FIGURE THAT CAN
%%% BE MANIPULATED
function [] = p3_call(varargin)

folder_path = uigetdir;
file_name = inputdlg('Save file as: ');
while isempty(file_name)
   file_name = input('File name needed.  Save file as: '); 
end

ax_old = gca;
f_new = figure('NumberTitle','off');
ax_new = copyobj(ax_old, f_new);
set(ax_new,'Position','default');
file = strcat(folder_path,'/',file_name{1},'.png');
print(f_new,'-dpng',file)

